// Generated by purs version 0.14.1
"use strict";
var $foreign = require("./foreign.js");
module.exports = {
    bold: $foreign.bold,
    italic: $foreign.italic,
    underline: $foreign.underline,
    mkList: $foreign.mkList,
    mkHeading: $foreign.mkHeading,
    indent: $foreign.indent
};
