// Generated by purs version 0.14.1
"use strict";
var touchstart = "touchstart";
var touchmove = "touchmove";
var touchend = "touchend";
var touchcancel = "touchcancel";
module.exports = {
    touchstart: touchstart,
    touchend: touchend,
    touchmove: touchmove,
    touchcancel: touchcancel
};
