// Generated by purs version 0.14.1
"use strict";
var $foreign = require("./foreign.js");
module.exports = {
    identifier: $foreign.identifier,
    screenX: $foreign.screenX,
    screenY: $foreign.screenY,
    clientX: $foreign.clientX,
    clientY: $foreign.clientY,
    pageX: $foreign.pageX,
    pageY: $foreign.pageY,
    target: $foreign.target
};
