// Generated by purs version 0.14.1
"use strict";
var compositionupdate = "compositionupdate";
var compositionstart = "compositionstart";
var compositionend = "compositionend";
module.exports = {
    compositionstart: compositionstart,
    compositionupdate: compositionupdate,
    compositionend: compositionend
};
